imports:
    - php

tools:
    external_code_coverage:
        timeout: 2100
        runs: 8

filter:
    excluded_paths:
        - SEOstats/*
        - vendor/*
        - tests/*
        - app/*
        - bin/*
